services:
  - type: web
    name: meetclone-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "daphne -b 0.0.0.0 -p $PORT meetclone.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
