# Generated by Django 6.1 on 2026-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
