# Generated by Django 6.1 on 2026-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
