# Generated by Django 5.2.3 on 2026-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='waiting_room_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
